# Check linter

name: eslint-check

on:
  push:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run make install 
        run: make install
              
      - name: Run make lint
        run: make lint
